### PR TITLE
Made the Site into a React App

### PR DESCRIPTION
**Pull request by lemokami**
Hope I helped you

### CODE REVIEW

**Comment by R-Aravind** [comment]
Hi @Jesswinw 
Please update the PR by adding some documentation for future maintainers.

**Comment by lemokami** [comment]
**OK Will Do!!!** 😉😉

**Comment by lemokami** [comment]
### Added some docs for the future 🤗

**Comment by R-Aravind** [comment]
Looks good. Good job @Jesswinw

**Comment by lemokami** [comment]
Well, **Happy to Help** ♥️

**Pull request merged**
